{% set name = "LoopStructural" %}
{% set version = "1.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/loopstructural-{{ version }}.tar.gz
  sha256: 0aab6b5527eb5f42ec87801f89ad2e7e46ba15b8c154831cc85886b5d1cd2acf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - numpy >=1.18
    - pandas
    - scipy
    - scikit-image
    - scikit-learn
    - tqdm

test:
  imports:
    - LoopStructural
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://loop3d.org/LoopStructural
  license: MIT
  license_file: LICENSE
  summary: LoopStructural is an implicit 3D structural geological modelling library for complex structural geology.
extra:
  recipe-maintainers:
    - lachlangrose
